server:
  port: 8888
  address: 0.0.0.0

spring:
  application:
    name: sample-app
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
    banner-mode: off

vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,unibos

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    influx:
      export:
        enabled: false
